"""
Backtest Report Generator.
Formats backtest simulation results into a clean, comprehensive Markdown audit report.
"""

from typing import Dict, Any


def generate_backtest_report(backtest_results: Dict[str, Any]) -> str:
    """
    Generates a professional Markdown performance report.
    """
    metrics = backtest_results.get("metrics", {})
    init_cap = backtest_results.get("initial_capital", 500000.0)
    final_cap = backtest_results.get("final_capital", init_cap)
    trades = backtest_results.get("trades", [])

    win_rate = metrics.get("win_rate_pct", 0.0)
    pf = metrics.get("profit_factor", 0.0)
    max_dd = metrics.get("max_drawdown_pct", 0.0)
    total_pnl = metrics.get("total_pnl", 0.0)
    sharpe = metrics.get("sharpe_ratio", 0.0)
    calmar = metrics.get("calmar_ratio", 0.0)
    expectancy = metrics.get("expectancy_rupees", 0.0)

    # Verification against targets
    target_checks = [
        ("Win Rate", f"{win_rate}%", ">= 55.0%", win_rate >= 55.0),
        ("Profit Factor", f"{pf}", "> 1.50", pf > 1.50),
        ("Max Drawdown", f"{max_dd}%", "< 10.0%", max_dd < 10.0),
        ("Expectancy", f"₹{expectancy}", "> 0", expectancy > 0),
    ]

    all_targets_met = all(c[3] for c in target_checks)
    overall_status = "PASSED ✅" if all_targets_met else "REVIEW REQUIRED ⚠️"

    report = f"""# Algorithmic Trading Strategy — Backtest Performance Audit

**Audit Status:** {overall_status}  
**Initial Capital:** ₹{init_cap:,.2f}  
**Ending Capital:** ₹{final_cap:,.2f}  
**Total Net P&L:** ₹{total_pnl:,.2f} ({metrics.get('return_on_capital_pct', 0.0)}%)

---

## 1. Executive Performance Scorecard

| Metric | Backtest Result | Target Benchmark | Audit Status |
|---|---|---|---|
"""
    for name, actual, target, passed in target_checks:
        status_icon = "PASS ✅" if passed else "FAIL ❌"
        report += f"| **{name}** | {actual} | {target} | {status_icon} |\n"

    report += f"""
---

## 2. Statistical Metrics Breakdown

| Indicator | Value |
|---|---|
| **Total Completed Trades** | {metrics.get('total_trades', 0)} |
| **Winning Trades** | {metrics.get('winning_trades', 0)} |
| **Losing Trades** | {metrics.get('losing_trades', 0)} |
| **Average Win** | ₹{metrics.get('avg_win', 0.0):,.2f} |
| **Average Loss** | ₹{metrics.get('avg_loss', 0.0):,.2f} |
| **Realized Risk/Reward Ratio** | 1 : {metrics.get('risk_reward_achieved', 0.0)} |
| **Max Peak-to-Trough Drawdown** | ₹{metrics.get('max_drawdown_rupees', 0.0):,.2f} ({max_dd}%) |
| **Annualized Sharpe Ratio** | {sharpe} |
| **Calmar Ratio** | {calmar} |
| **Mathematical Expectancy / Trade** | ₹{expectancy:,.2f} |

---

## 3. Recent Trades Log (Sample)

| # | Strategy | Direction | Entry Price | Exit Price | Reason | Net P&L |
|---|---|---|---|---|---|---|
"""
    for idx, t in enumerate(trades[-10:], start=max(1, len(trades) - 9)):
        pnl = t.get("pnl", 0)
        pnl_str = f"+₹{pnl:,.2f}" if pnl >= 0 else f"-₹{abs(pnl):,.2f}"
        report += f"| {idx} | {t.get('strategy', 'Spread')} | {t.get('direction')} | {t.get('entry_price')} | {t.get('exit_price')} | {t.get('exit_reason')} | {pnl_str} |\n"

    report += "\n*Report auto-generated by BacktestRunner.*\n"
    return report
